### ISSUE TITLE
Add CI to generate diff remotely

### ISSUE THREAD

**Issue by JoaoGH** [gustavoharff/grails-diffs#3]
Create a pipeline to generate Grails version differences without running local.

**Comment by JoaoGH** [comment]
please provide an explanation of how the repository works.

por favor, forneça uma explicação do funcionamento do repositorio.

@gustavoharff

**Comment by gustavoharff** [comment]
Of course @JoaoGH

The repository basically uses three branches:

`main`:  It has the available generated diffs list and the script to generate them.
`base`: A simple branch to create Grails applications and perform tag generation.
`diffs`: Place where all generated diffs are saved.

The script was created to be able to provide the `profile` and `type` of the application at the time of generating the diffs.

- `profile`: **rest-api-plugin** or **web-plugin** (for type = plugin) and **rest-api** or **web** (for type = app)
  - The profile **plugin** also exists, but i didn't implemented, that would be good too.

- `type`: **plugin** or **app**

I recommend create a fork for you work, the main script create new commits, branches and tags.

You need to create Github Actions that run in sequence and not at the same time, so one doesn't disturb the other.

**Comment by gustavoharff** [comment]
This task has done.

https://github.com/gustavoharff/grails-diffs/blob/main/.github/workflows/new-release.yml
